### ISSUE TITLE
globalStore app.js 引入问题

### ISSUE THREAD

**Issue by zouxianbincc** [linjc/dd-store#2]
按照你在app.js 中的，引入globalStore ，但是编译说没有定义，用的是微信原生开发工具

**Comment by linjc** [comment]
目前只支持钉钉小程序，没有兼容微信小程序

**Comment by linjc** [comment]
@zouxianbincc 目前只支持钉钉小程序，没有兼容微信小程序

**Comment by linjc** [comment]
@zouxianbincc 目前只支持钉钉小程序，没有兼容微信小程序。如果要使用可以下载src/create.js，将didMount替换为ready，didUnmount替换为detached。
