### ISSUE TITLE
想问下能否在支付宝小程序中使用这个库

### ISSUE THREAD

**Issue by javaSwing** [linjc/dd-store#3]
## 我现在在支付宝小程序中使用这个库，遇到如下问题
1. 如果data中有数组类型会报错。
![image](https://user-images.githubusercontent.com/7713463/70885429-c3d1de80-2013-11ea-8767-a87928cd6c12.png)
![image](https://user-images.githubusercontent.com/7713463/70885441-c9c7bf80-2013-11ea-9363-c33b2354831f.png)

其中globalStore为空的
![image](https://user-images.githubusercontent.com/7713463/70885518-04315c80-2014-11ea-8902-5a09466ac766.png)

**Comment by javaSwing** [comment]
补充下，错误的位置在
![image](https://user-images.githubusercontent.com/7713463/70885605-48bcf800-2014-11ea-82fc-0c3c6096a1e0.png)

**Comment by linjc** [comment]
@javaSwing 可以在支付宝使用的，和钉钉没区别，你这个问题是使用store，但store.data没有设置字段导致的，算是一个bug吧，我考虑到这种情况，后续我优化下。你现在先在store.data加个字段试试。

**Comment by linjc** [comment]
@javaSwing 可以在支付宝使用的，和钉钉没区别，你这个问题是使用store，但store.data没有设置字段导致的，算是一个bug吧，我没考虑到这种情况，后续我优化下。你现在先在store.data加个字段试试，或者把tabs字段移到store.data内。

**Comment by javaSwing** [comment]
@linjc 我添加了也是一样的，好像是diff时没有把tabs这个属性给过滤了，重复设置导致的

**Comment by linjc** [comment]
@javaSwing 你现在用的是哪个版本的

**Comment by javaSwing** [comment]
@linjc 1.7.0

**Comment by linjc** [comment]
@javaSwing 好的，你试试改用1.6.0有没有问题，我这边先排查下。方便的话，加钉钉linjinchun聊

**Comment by linjc** [comment]
@javaSwing 问题已修复，这个问题只在支付宝loT小程序出现，已在1.7.4版本添加了兼容

**Comment by javaSwing** [comment]
@linjc 好的收到
