### ISSUE TITLE
怎么在当前页监听数据更新然后执行相应的方法函数

### ISSUE THREAD

**Issue by click-me1991** [linjc/dd-store#6]
经常遇到，需要监听用户有没有登录完成，然后执行相应的业务方法；在一个页面怎么监听store里的数据已经更新然后执行相应的方法

**Comment by linjc** [comment]
这个问题比较常见，可以通过自定义一个ready函数去实现，原理类似微信或钉钉等h5 jsapi的ready函数。
```js
authReady(function() {
  // 登录成功后执行
})
```

**Comment by linjc** [comment]
暂时没有

**Comment by linjc** [comment]
onLoad取不到store？目前验证没出现过这个问题。另外页面上store只是一个引用，任何时候取到都是store当前最新的值，如果是异步更新值，可以在异步回调之后再做相应操作。

**Comment by click-me1991** [comment]
不好意思，问题找到了，钉钉小程序现在还不支持分包,泪目~
